-- Creating table for actors
CREATE TABLE actors (
    id INT AUTO_INCREMENT PRIMARY KEY,
    firstname VARCHAR(100) NOT NULL,
    lastname VARCHAR(100) NOT NULL,
    bio TEXT NOT NULL,
    rating DECIMAL(3,1) NOT NULL
);

-- Inserting 100 actors with random ratings (1.0-10.0)
INSERT INTO actors (firstname, lastname, bio, rating) VALUES
('Emma', 'Stone', 'Known for her versatile roles in both drama and comedy, she captivates audiences with her charm.', 8.7),
('Liam', 'Neeson', 'An action star with a commanding presence, famous for intense performances.', 7.4),
('Sophia', 'Loren', 'A legendary actress with a career spanning decades, known for her elegance.', 9.2),
('Denzel', 'Washington', 'Renowned for powerful performances in dramatic roles, a true icon.', 8.9),
('Meryl', 'Streep', 'Celebrated for her unmatched range and transformative acting skills.', 9.5),
('Tom', 'Hanks', 'Beloved for his heartfelt performances and relatable characters.', 8.3),
('Natalie', 'Portman', 'An Oscar winner known for her intense and nuanced portrayals.', 7.8),
('Chris', 'Hemsworth', 'A charismatic action star, best known for his superhero roles.', 6.9),
('Viola', 'Davis', 'A powerhouse performer with gripping emotional depth.', 9.1),
('Ryan', 'Gosling', 'Known for his brooding intensity and versatile roles.', 8.0),
('Scarlett', 'Johansson', 'A versatile actress excelling in both action and drama.', 7.6),
('Robert', 'Downey', 'Famous for his witty and charismatic performances.', 8.2),
('Zendaya', 'Coleman', 'A rising star with a strong presence in film and television.', 7.3),
('Leonardo', 'DiCaprio', 'Known for his intense roles and environmental advocacy.', 8.8),
('Margot', 'Robbie', 'A dynamic actress known for bold and captivating performances.', 7.9),
('Brad', 'Pitt', 'A Hollywood icon with a blend of charm and gravitas.', 8.1),
('Angelina', 'Jolie', 'Known for her striking presence and humanitarian work.', 7.5),
('Johnny', 'Depp', 'Famous for his eccentric and transformative roles.', 6.8),
('Keira', 'Knightley', 'Renowned for her period drama roles and elegant performances.', 7.2),
('Will', 'Smith', 'A charismatic star known for action and heartfelt roles.', 8.4),
('Tessa', 'Thompson', 'A versatile actress with a strong presence in sci-fi and drama.', 7.7),
('Hugh', 'Jackman', 'Known for his dynamic range in musicals and action films.', 8.0),
('Jennifer', 'Lawrence', 'An Oscar winner with a knack for relatable characters.', 7.4),
('Christian', 'Bale', 'Famous for his transformative roles and intense dedication.', 8.6),
('Florence', 'Pugh', 'A rising star known for her powerful and nuanced performances.', 7.9),
('Matt', 'Damon', 'Known for his everyman charm and action roles.', 8.3),
('Charlize', 'Theron', 'A versatile actress excelling in action and dramatic roles.', 7.8),
('Idris', 'Elba', 'A commanding presence known for his intense performances.', 8.1),
('Anne', 'Hathaway', 'Known for her emotional depth and versatile roles.', 7.6),
('Joaquin', 'Phoenix', 'Famous for his intense and transformative performances.', 8.9),
('Reese', 'Witherspoon', 'A beloved actress known for her charm and producing work.', 7.3),
('Chris', 'Evans', 'Known for his heroic roles and relatable charm.', 7.5),
('Saoirse', 'Ronan', 'A young star with remarkable depth in dramatic roles.', 8.2),
('Mark', 'Ruffalo', 'Known for his heartfelt and nuanced performances.', 7.7),
('Gal', 'Gadot', 'A charismatic actress known for action-packed roles.', 7.0),
('Benedict', 'Cumberbatch', 'Famous for his intellectual and intense characters.', 8.4),
('Anya', 'Taylor-Joy', 'A rising star with a unique and captivating presence.', 7.8),
('Tom', 'Hardy', 'Known for his intense and transformative performances.', 8.5),
('Emily', 'Blunt', 'A versatile actress excelling in both comedy and drama.', 7.9),
('Ryan', 'Reynolds', 'Famous for his witty and comedic performances.', 7.4),
('Tilda', 'Swinton', 'Known for her eclectic and bold role choices.', 8.1),
('Daniel', 'Craig', 'Famous for his gritty and intense action roles.', 7.6),
('Cate', 'Blanchett', 'A masterful actress with a commanding presence.', 9.0),
('Chris', 'Pine', 'Known for his charming and heroic roles.', 7.3),
('Halle', 'Berry', 'A versatile actress known for action and dramatic roles.', 7.1),
('Jake', 'Gyllenhaal', 'Famous for his intense and varied performances.', 8.2),
('Amy', 'Adams', 'Known for her emotional and versatile roles.', 7.8),
('Henry', 'Cavill', 'A charismatic actor known for action and fantasy roles.', 7.5),
('Lupita', 'Nyong''o', 'A powerful actress known for her emotional depth.', 8.3),
('Michael', 'Fassbender', 'Famous for his intense and magnetic performances.', 8.0),
('Alicia', 'Vikander', 'Known for her nuanced and powerful performances.', 7.7),
('Timothée', 'Chalamet', 'A young star with remarkable emotional range.', 8.1),
('Gwyneth', 'Paltrow', 'Known for her elegant and versatile roles.', 7.4),
('Paul', 'Rudd', 'Famous for his comedic charm and likable characters.', 7.2),
('Lily', 'James', 'A rising star known for her period drama roles.', 7.6),
('Andrew', 'Garfield', 'Known for his emotional and intense performances.', 8.2),
('Jessica', 'Chastain', 'A versatile actress with powerful dramatic roles.', 8.0),
('Eddie', 'Redmayne', 'Famous for his transformative and heartfelt roles.', 7.8),
('Zoe', 'Saldana', 'Known for her dynamic roles in sci-fi and action films.', 7.5),
('Oscar', 'Isaac', 'A versatile actor with intense and nuanced performances.', 8.3),
('Emma', 'Watson', 'Known for her iconic roles and advocacy work.', 7.2),
('Colin', 'Firth', 'Famous for his refined and emotional performances.', 7.9),
('Millie', 'Bobby Brown', 'A young star known for her sci-fi and action roles.', 7.4),
('Sam', 'Worthington', 'Known for his action-packed and heroic roles.', 7.1),
('Daisy', 'Ridley', 'A rising star known for her sci-fi and fantasy roles.', 7.6),
('Rami', 'Malek', 'Famous for his transformative and intense performances.', 8.1),
('Kate', 'Winslet', 'Known for her emotional depth and versatile roles.', 8.4),
('John', 'Boyega', 'A dynamic actor known for his sci-fi roles.', 7.3),
('Rooney', 'Mara', 'Known for her intense and nuanced performances.', 7.8),
('Jason', 'Momoa', 'Famous for his commanding presence in action roles.', 7.5),
('Kristen', 'Stewart', 'Known for her bold and varied role choices.', 7.7),
('Chiwetel', 'Ejiofor', 'A powerful actor known for his dramatic roles.', 8.2),
('Brie', 'Larson', 'An Oscar winner known for her intense performances.', 7.9),
('Tom', 'Holland', 'A young star known for his energetic and heroic roles.', 7.4),
('Olivia', 'Colman', 'Known for her versatile and emotional performances.', 8.5),
('Adam', 'Driver', 'Famous for his intense and nuanced roles.', 8.3),
('Rachel', 'McAdams', 'Known for her charming and emotional performances.', 7.6),
('Jared', 'Leto', 'Famous for his transformative and bold roles.', 7.2),
('Carey', 'Mulligan', 'Known for her nuanced and heartfelt performances.', 7.8),
('Ben', 'Affleck', 'A versatile actor known for action and drama.', 7.5),
('Michelle', 'Williams', 'Known for her emotional and powerful performances.', 8.0),
('Daniel', 'Kaluuya', 'A rising star with intense and dynamic roles.', 8.2),
('Keenu', 'Reeves', 'Famous for his action roles and likable persona.', 7.7),
('Julianne', 'Moore', 'Known for her versatile and emotional performances.', 8.1),
('Mahershala', 'Ali', 'A powerful actor known for his dramatic roles.', 8.4),
('Emilia', 'Clarke', 'Known for her fantasy and dramatic roles.', 7.6),
('James', 'McAvoy', 'Famous for his intense and varied performances.', 7.9),
('Laura', 'Dern', 'Known for her versatile and emotional roles.', 8.0),
('Josh', 'Brolin', 'A versatile actor known for action and drama.', 7.5),
('Elizabeth', 'Olsen', 'Known for her dynamic roles in sci-fi and drama.', 7.7),
('Cillian', 'Murphy', 'Famous for his intense and nuanced performances.', 8.3),
('Naomi', 'Watts', 'Known for her emotional and dramatic roles.', 7.8),
('Chris', 'Pratt', 'A charismatic actor known for action and comedy.', 7.4),
('Robin', 'Wright', 'Known for her commanding and versatile roles.', 7.9),
('Jamie', 'Foxx', 'A versatile actor known for his dynamic performances.', 8.1),
('Anna', 'Kendrick', 'Known for her comedic and musical roles.', 7.3),
('Benicio', 'Del Toro', 'Famous for his intense and transformative roles.', 8.0),
('Felicity', 'Jones', 'Known for her emotional and dynamic performances.', 7.6),
('Patrick', 'Stewart', 'A legendary actor known for his commanding presence.', 8.2),
('Sienna', 'Miller', 'Known for her elegant and versatile roles.', 7.5);