-- Creating table for movies
CREATE TABLE movies (
    id INT AUTO_INCREMENT PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    year INT NOT NULL,
    description TEXT NOT NULL,
    rating DECIMAL(3,1) NOT NULL
);

-- Inserting 100 movies with random years (1920-2025), descriptions, and ratings (1.0-10.0)
INSERT INTO movies (title, year, description, rating) VALUES
('The Silent Voyage', 1945, 'A gripping tale of a lone sailor navigating treacherous waters during WWII.', 7.8),
('Echoes of Tomorrow', 1998, 'A sci-fi adventure exploring a dystopian future where time travel is outlawed.', 4.2),
('Crimson Horizon', 1967, 'A western showdown between rival outlaws in a desert town.', 9.1),
('Whispers in the Dark', 2005, 'A psychological thriller about a detective unraveling a series of cryptic murders.', 6.3),
('Starlight Serenade', 1932, 'A romantic musical set in the glamorous world of 1930s Broadway.', 3.9),
('Moonlit Shadows', 1983, 'A haunting drama about a family confronting their dark past.', 8.4),
('The Forgotten Realm', 2010, 'A fantasy epic where a young hero must save a magical kingdom.', 5.7),
('Eternal Flame', 1954, 'A passionate love story set against the backdrop of a war-torn city.', 7.2),
('Desert Mirage', 1976, 'An adventure film about explorers lost in a mysterious desert.', 2.8),
('Skyward Dreams', 2020, 'A coming-of-age story about a teen pursuing her dream of becoming an astronaut.', 9.5),
('Velvet Dawn', 1940, 'A noir mystery involving a private detective and a dangerous femme fatale.', 6.1),
('Neon Nights', 1995, 'A cyberpunk thriller set in a futuristic city ruled by corporations.', 4.9),
('Golden Abyss', 1962, 'A treasure-hunting adventure in the jungles of South America.', 8.7),
('Twilight Echo', 2008, 'A romantic drama about two lovers separated by fate.', 3.4),
('Crystal Voyage', 1980, 'A sci-fi odyssey following a crew exploring an uncharted galaxy.', 7.6),
('Silent Reverie', 1950, 'A poetic drama about a mute artist finding her voice through painting.', 5.2),
('Starborn Legacy', 2015, 'A space opera about a young pilot destined to save the universe.', 9.3),
('Midnight Tide', 1972, 'A suspenseful tale of a coastal town plagued by mysterious disappearances.', 4.5),
('Ember Skies', 1990, 'A post-apocalyptic story of survival in a scorched world.', 6.8),
('The Lost Symphony', 1938, 'A historical drama about a composer struggling during the Great Depression.', 8.1),
('Aurora Veil', 2002, 'A fantasy tale of a warrior princess defending her kingdom.', 3.7),
('Phantom Horizon', 1965, 'A war film depicting a squad’s perilous mission behind enemy lines.', 7.4),
('Celestial Drift', 2018, 'A sci-fi drama about a drifting spaceship and its lone survivor.', 5.9),
('Shadowed Path', 1948, 'A noir thriller about a man framed for a crime he didn’t commit.', 9.0),
('Eclipsed Dreams', 1985, 'A coming-of-age story set in the vibrant 1980s music scene.', 4.3),
('Radiant Echoes', 2000, 'A drama about a family reuniting after years of estrangement.', 6.6),
('Mystic River', 1970, 'A mystery film about a detective solving a case by a haunted river.', 8.2),
('Dawn of Valor', 1955, 'A war epic about soldiers fighting for freedom in a brutal conflict.', 3.1),
('Nightfall Saga', 2012, 'A fantasy adventure about a group of heroes battling an ancient evil.', 7.9),
('Starlit Haven', 1992, 'A romantic comedy set in a quaint seaside village.', 5.4),
('Veil of Secrets', 1960, 'A spy thriller set during the Cold War.', 9.4),
('Crimson Quest', 2007, 'An action-packed adventure following a knight on a holy mission.', 4.7),
('Whispering Sands', 1982, 'A desert survival story about a stranded pilot.', 6.5),
('Eternal Horizon', 1942, 'A wartime romance between a soldier and a nurse.', 8.8),
('Moonlit Quest', 1997, 'A fantasy tale of a young mage seeking a legendary artifact.', 3.6),
('Silent Dawn', 1975, 'A drama about a small town recovering from a tragedy.', 7.3),
('Twilight Realm', 2019, 'A sci-fi epic about a rebellion against an alien empire.', 5.8),
('Golden Mirage', 1952, 'An adventure film about a treasure hunt in the Sahara.', 9.2),
('Neon Echo', 2003, 'A cyber-thriller about a hacker uncovering a global conspiracy.', 4.4),
('Starlight Odyssey', 1968, 'A space exploration film with stunning visuals.', 6.7),
('Desert Symphony', 1988, 'A drama about a musician finding inspiration in a remote desert.', 8.3),
('Velvet Shadows', 1947, 'A noir mystery involving a missing heiress.', 3.8),
('Crystal Tide', 2010, 'A fantasy adventure about a mermaid protecting her underwater kingdom.', 7.7),
('Midnight Voyage', 1978, 'A thriller about a ship lost in a stormy sea.', 5.3),
('Ember Horizon', 1993, 'A post-apocalyptic tale of a lone wanderer seeking redemption.', 9.1),
('The Silent Path', 1957, 'A drama about a monk’s spiritual journey in a war-torn land.', 4.6),
('Aurora Legacy', 2006, 'A fantasy epic about a queen reclaiming her throne.', 6.9),
('Phantom Dreams', 1980, 'A surreal film exploring the boundaries of reality and dreams.', 8.5),
('Celestial Echo', 1963, 'A sci-fi drama about a signal from an unknown planet.', 3.5),
('Shadowed Veil', 2014, 'A thriller about a journalist uncovering a political scandal.', 7.1),
('Eclipsed Saga', 1940, 'A historical drama set during a solar eclipse.', 5.6),
('Radiant Dawn', 1999, 'A coming-of-age story about a young artist in a vibrant city.', 9.0),
('Mystic Horizon', 1974, 'A mystical tale of a shaman guiding a lost soul.', 4.8),
('Dawn of Secrets', 2001, 'A mystery about a detective solving a decades-old case.', 6.4),
('Nightfall Echoes', 1953, 'A noir film about a detective haunted by his past.', 8.6),
('Starlit Mirage', 2017, 'A fantasy adventure about a hero seeking a hidden realm.', 3.9),
('Veil of Valor', 1966, 'A war film about a soldier’s bravery in a hopeless battle.', 7.5),
('Crimson Path', 1987, 'An action film about a samurai seeking revenge.', 5.1),
('Whispering Quest', 2004, 'A fantasy tale of a young adventurer seeking a lost city.', 9.3),
('Eternal Shadows', 1949, 'A noir thriller about a man on the run from his past.', 4.2),
('Moonlit Symphony', 1996, 'A musical drama about a composer’s rise to fame.', 6.8),
('Silent Horizon', 1971, 'A drama about a pilot stranded in a remote wilderness.', 8.4),
('Twilight Voyage', 2011, 'A sci-fi adventure about a crew exploring a distant planet.', 3.7),
('Golden Echo', 1958, 'A historical drama about a family during the Gold Rush.', 7.0),
('Neon Realm', 2000, 'A cyberpunk thriller about a virtual reality conspiracy.', 5.5),
('Starlight Path', 1964, 'A romantic drama about two lovers meeting under the stars.', 9.5),
('Desert Dreams', 1989, 'An adventure about explorers uncovering an ancient ruin.', 4.3),
('Velvet Tide', 1943, 'A wartime romance set on a stormy coastline.', 6.7),
('Crystal Saga', 2009, 'A fantasy epic about a hero wielding a magical crystal.', 8.2),
('Midnight Mirage', 1977, 'A thriller about a man lost in a desert hallucination.', 3.4),
('Ember Veil', 1994, 'A post-apocalyptic drama about a community rebuilding.', 7.8),
('The Silent Dawn', 1961, 'A drama about a village recovering from a natural disaster.', 5.9),
('Aurora Quest', 2013, 'A fantasy adventure about a knight seeking a mythical relic.', 9.1),
('Phantom Echo', 1946, 'A noir mystery about a detective chasing a ghost.', 4.5),
('Celestial Horizon', 2002, 'A sci-fi tale of a colony on a distant planet.', 6.6),
('Shadowed Symphony', 1973, 'A drama about a musician haunted by his past.', 8.7),
('Eclipsed Tide', 1991, 'A romance set during a rare astronomical event.', 3.8),
('Radiant Voyage', 1955, 'An adventure about a sailor exploring uncharted islands.', 7.4),
('Mystic Shadows', 2016, 'A fantasy thriller about a sorcerer battling dark forces.', 5.2),
('Dawn of Echoes', 1969, 'A drama about a family reuniting after a tragedy.', 9.0),
('Nightfall Dreams', 1984, 'A surreal film exploring the dreams of a troubled artist.', 4.7),
('Starlit Saga', 2005, 'A fantasy epic about a hero destined to save the world.', 6.9),
('Veil of Horizon', 1941, 'A wartime drama about a spy infiltrating enemy lines.', 8.3),
('Crimson Quest', 1998, 'An action adventure about a warrior seeking a lost artifact.', 3.6),
('Whispering Tide', 1970, 'A mystery about a coastal town and its dark secrets.', 7.7),
('Eternal Tide', 2010, 'A romantic drama about lovers separated by time.', 5.4),
('Moonlit Veil', 1954, 'A noir romance about a detective and a mysterious woman.', 9.2),
('Silent Echo', 2003, 'A thriller about a journalist uncovering a conspiracy.', 4.8),
('Twilight Mirage', 1967, 'A fantasy tale of a kingdom hidden in the mist.', 6.5),
('Golden Symphony', 1986, 'A musical drama about a composer’s rise to fame.', 8.1),
('Neon Horizon', 1948, 'A noir thriller set in a bustling post-war city.', 3.9),
('Starlight Dreams', 2007, 'A romantic comedy about two aspiring actors.', 7.3),
('Desert Echo', 1975, 'An adventure about a lost explorer in a vast desert.', 5.7),
('Velvet Saga', 1995, 'A historical epic about a royal family’s legacy.', 9.4),
('Crystal Path', 1962, 'A fantasy adventure about a hero seeking a magical path.', 4.4),
('Midnight Quest', 2012, 'An action film about a treasure hunter’s perilous journey.', 6.8),
('Ember Dawn', 1950, 'A drama about a town rebuilding after a fire.', 8.5),
('The Silent Tide', 2000, 'A mystery about a sailor lost at sea.', 3.7),
('Aurora Symphony', 1978, 'A musical drama about a composer’s final masterpiece.', 7.6),
('Phantom Veil', 1990, 'A thriller about a detective chasing a ghostly figure.', 5.3);